package ec.edu.uce.FabricaMusical.models.enums;

public enum Steps {
    COMPRAR_MATERIALES,
    INSPECCION_DE_CALIDAD_MATERIALES,
    CORTAR,
    TALLAR,
    MOLDEAR_FORMA,
    LIJADO,
    PULIDO,
    PINTAR,
    BARNIZADO,
    SECADO,
    ENSAMBLAJE_DE_COMPONENTES,
    SOLDAR_PIEZAS_METALICAS,
    MONTAJE_DE_PIEZAS_ELECTRONICAS,
    INSTALACION_DE_CUERDAS,
    INSTALACION_DE_TECLAS,
    COLOCAR_MEMBRANA_DE_PERCUSION,
    AFINACION,
    CALIBRACION,
    PRUEBAS_DE_SONIDO,
    PRUEBAS_DE_FUNCIONAMIENTO_ELECTRICO,
    PRUEBAS_DE_FUNCIONAMIENTO_MECANICO,
    EMPAQUETADO_Y_ETIQUETADO,
    ALMACENAMIENTO_FINAL
}